### ISSUE TITLE
Internal Server Error on return from Steam login

### ISSUE THREAD

**Issue by SummitV12** [zeropingheroes/lanager#145]
Fresh install, fixed an issue with my URL not being correct, but on return from the Steam login page, I get returned to a Lanager Internal Server Error page.
URL returned by Steam was: http://lanager.summit.net/auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198088089043&openid.identity=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198088089043&openid.return_to=http%3A%2F%2Flanager.summit.net%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2022-05-05T17%3A56%3A21ZRazEQKdzFATcm0uHq%2BO%2F0sn6dTw%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=bW7qXq5ZoQ5X7ioza0VcRBSyQys%3D

Logs:
```[2022-05-05 16:12:13] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/lanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:168)
[stacktrace]
#0 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(102): Illuminate\\Log\\LogManager->resolve()
#1 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(90): Illuminate\\Log\\LogManager->get()
#2 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(500): Illuminate\\Log\\LogManager->driver()
#3 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(118): Illuminate\\Log\\LogManager->error()
#4 /var/www/lanager/app/Exceptions/Handler.php(44): Illuminate\\Foundation\\Exceptions\\Handler->report()
#5 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(378): Zeropingheroes\\Lanager\\Exceptions\\Handler->report()
#6 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(143): Illuminate\\Foundation\\Console\\Kernel->reportException()
#7 /var/www/lanager/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 
[2022-05-05 16:12:13] laravel.ERROR: syntax error, unexpected 'Syntax' (T_STRING), expecting ']' {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'Syntax' (T_STRING), expecting ']' at /var/www/lanager/config/app.php:154)
[stacktrace]
#0 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(39): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->loadConfigurationFiles()
#1 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\LoadConfiguration->bootstrap()
#2 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(322): Illuminate\\Foundation\\Application->bootstrapWith()
#3 /var/www/lanager/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#4 /var/www/lanager/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#5 {main}
"} ```

**Comment by SummitV12** [comment]
Used the wrong version of PHP (7.4). Seemed to fix with 7.2
